cheeseFacts = [
    'Cheese is a dairy! It is the resulting product of curdling milk. In cheese factories, bacteria is added to milk to convert the lactose into lactic acid, and then an enzyme is added, which curdles the milk. This enzyme is called rennet, which used to be taken from the stomachs of young cows but is now found from genetically engineered bacteria and yeast.',
    'It takes about 10 pounds of milk to make 1 pound of cheese, though this ratio changes depending on the type of milk.',
    'Cheddar cheese is not naturally yellow. The bright orange cheddar cheese we all know and love is not a natural result of its curdled milk components. All cheese is naturally white, off-white, or golden yellow (dependent on the milk). To get the orange color of cheddar cheese, like the irresistible cheese in our Chicago Baked Cheddar popcorn, flavorless Annatto seed is added.',
    'Gouda cheese accounts for 50-60% of the world’s consumption of cheese.',
    'The state which produces the most amount of cheese is Wisconsin. More than two and a half billion pounds of cheese are produced in Wisconsin every year. The next top producer is California.',
    'Cheese was discovered by accident! Ancient people more than 7000 years ago discovered cheese by carrying milk in the stomach linings of animals, which carried the bacteria rennet that curdles milk.',
    'The most popular cheese recipe in America is Mac and Cheese.',
    'There are about 2,000 varieties of cheese.',
    'The biggest and heaviest cheese ever created was 32 feet long and weighed 57,518 pounds! A Canadian cheese maker used 540,000 pounds of milk to make this record-breaking cheddar cheese.',
    'National Dairy month is in June.',
    'Cheese is one of the most popular flavors of popcorn nationwide.',
    '‘Cheese’ comes from the Latin word ‘caseus’, which has been found to mean ‘to ferment/to sour’.',
    'Cheese is made from the milk of cows, buffalo’s, goats, sheep, horses and camels.',
    'Some cheeses can be curdled by adding lemon juice or vinegar.',
    'There are many types of cheese such as hard cheese, soft cheese, cream cheese, and processed cheese, all which can be used in cooking.',
    'Blue cheese, which has distinctive smells and tastes, have blue veins running through, which is caused by piercing the cheese and its crust with stainless steel needles and copper wires, to allow air into the product.',
    'The US produces over 4275 tonnes of cheese a year. Germany produces 1927 tonnes, whereas France produces 1884 tonnes.',
    'Greece consumes over 31.1 kg of cheese a year. France consumes 26.1 kg, whereas Iceland consumes 25.4 kg.',
    'A seller of cheese is known as a ‘cheesemonger’.',
    'Those who are lactose intolerant (unable to process a type of sugar found in milk and milk products) should avoid eating cheese.',
    'It was once believed that eating cheese before bed could cause nightmares, but in fact it had health benefits.',
    'Collecting cheese labels is known as ‘tyrosemiophilia’.',
    'The famous characters Wallace and Gromit are partial to Wensleydale cheese on crackers.',
    'People once believed the proverb that ‘the moon is made of green cheese’.',
    'The most stolen food item in the world is cheese, with 4% of all cheese being sold end up stolen.',
    'President Andrew Jackson once had a block of cheddar cheese delivered to the white house that was four feet in diameter and two feet thick, weighed nearly 1400 pounds. He invited 10,000 visitors to the White House to eat it and it was gone within two hours.',
    'When cheese is digested, it breaks down into an opioid. Other opioids you may know about are heroin and morphine.',
    'The “holes” in Swiss cheese were, until recently, seen as a sign of imperfection and something cheese makers tried to avoid.',
    'Albertville, France’s electricity is powered by Beaufort cheese. Since whey is unnecessary to make Beaufort cheese, bacteria is added to the whey. This transforms the whey into biogas. This gas is then fed through an engine which heats water to 90°C (194°F) to generate 2800 MWh/yr of electricity.',
    'There’s a cheese from Sardinia with maggots in it that’s outlawed by European Union food hygiene-health regulations, however, it’s still made and sold on the black market.',
    'People started dying cheese orange back in the 17th century to fool people into thinking it was higher quality.',
    'Stilton blue cheese is known to frequently cause odd, vivid dreams.',
    'American Cheese cannot be legally sold as “cheese” in the United States. It must instead be labeled as “cheese product,” “cheese food,” or “American Singles,” since its manufacturing process varies so significantly from that of other cheeses.',
    'Philadelphia cream cheese is named after a village in upstate New York, not the famous Pennsylvania city.',
    'Scientists have successfully created cheese using human bacteria collected from toes and belly buttons.',
    'In the 2013 American Cheese Competition, only one cheese was entered in the Dry Jack category, it came in third. The judges chose to not award first or second.',
    'Cheese can be addictive, as it contains trace amounts of naturally occurring morphine, that comes from the cow’s liver.',
    'The crunchy bits you sometimes get inside of aged cheese are amino acid crystals.',
    'The French have a different cheese for every day of the year. Cheese experts estimate the total number of different French cheeses is around 1000.',
    'Västerbottensost, a prized cheese from Sweden, can only be made in one village (Burträsk). After forensic DNA tests, multiple scientific studies and several documentaries, nobody knows why.',
    'Kraft Singles cannot be called cheese because less than 51% of it is actually cheese.',
    'Moose cheese costs around $420 per pound, since each milking takes two hours, and must be done in complete silence.',
    'Pule cheese is the world’s most expensive cheese and it comes from the milk of Balkan donkeys from Serbia. It’s valued at $600 per pound; it’s so expensive because there are only ~100 jennies (female donkeys) that are milked for pule-making. It takes 3 gallons of milk to create 1 pound of cheese.',
    'Edam Cheese never goes bad, it only hardens. This resulted in its popularity at sea and in remote places.',
    'Sales of Wensleydale cheese strongly improved because of Wallace and Gromit, saving the cheese.'
]